In [1]:
# Import Libraries
import numpy as np

from project_utils.bb_model import BB_Model
from project_utils.feature_stats import Feature_Statistics
from project_utils.feature_stats import Regression_Container





In [2]:
# Load Boston model

Boston_Data = BB_Model('Boston')

Boston_Data.df().head()

<class 'ValueError'>: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
from sklearn.gaussian_process import GaussianProcessRegressor

from sklearn.gaussian_process.kernels import RBF
from sklearn.gaussian_process.kernels import Matern


RBF_kernel = RBF()
Matern_kernel = Matern()


GP = GaussianProcessRegressor(kernel=RBF_kernel, n_restarts_optimizer = 5, normalize_y = False)

X_train, X_test, y_train, y_test = Boston_Data.get_TT_data()

GP.fit(X_train, y_train)

score = GP.score(X_test, y_test)

print('Score: ', score)

In [7]:

X_row = np.array([X_test[2]])

y_predict, y_std = GP.predict(X_row, return_std=True)

print(y_test[2], ' : ', y_predict, ' : ', y_std)

23.2  :  [15.79702298]  :  [0.76033559]


In [8]:
# Load Diabetes model

Diabetes_Data = BB_Model('Diabetes')

Diabetes_Data.df().head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [9]:
from sklearn.gaussian_process import GaussianProcessClassifier

RBF_kernel = RBF()
Matern_kernel = Matern()

GP = GaussianProcessClassifier(kernel=Matern_kernel, n_restarts_optimizer = 5)

Xd_train, Xd_test, yd_train, yd_test = Diabetes_Data.get_TT_data()

GP.fit(Xd_train, yd_train)

score = GP.score(Xd_test, yd_test)

print('Score: ', score)

Score:  0.7727272727272727


In [10]:
Xd_row = np.array([Xd_test[2]])

yd_predict = GP.predict_proba(Xd_row)

print(yd_test[2], ' : ', yd_predict)

1  :  [[0.57802717 0.42197283]]


In [11]:
x=np.array([1,2,3,4])
y=np.array([8,0,5,2])

In [12]:
x-y

array([-7,  2, -2,  2])

In [13]:
x*y

array([ 8,  0, 15,  8])

In [14]:
z = [[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]]

In [15]:
np.std(z,axis=0)

array([1.11803399, 1.11803399, 1.11803399, 1.11803399])

In [16]:
np.std(z,axis=1)

array([0., 0., 0., 0.])

In [17]:
np.mean(z,axis=0)

array([2.5, 2.5, 2.5, 2.5])

In [18]:
np.mean(z,axis=1)

array([1., 2., 3., 4.])