In [1]:
import numpy as np

In [20]:
a = np.array([[1, 4, -2],[6 , 4 , 3]])

b = np.array([[3, 4, 1],[6 , 2 , 1]])

c = np.array([6,10, 1, 9, 3])

In [21]:
x = a - b

print(x)

[[-2  0 -3]
 [ 0  2  2]]


In [22]:
z = np.square(x)

print(z)

[[4 0 9]
 [0 4 4]]


In [23]:
y = np.square(a - b)

print(y)

[[4 0 9]
 [0 4 4]]


In [24]:
print(np.mean(y))

3.5


In [25]:
print(c.argmax())

1
