In [1]:
import numpy as np

In [4]:
f_pred = np.random.rand(10,2)
f_pred[:,1] = 1 - f_pred[:,0]

print(f_pred)


[[0.39474817 0.60525183]
 [0.10005893 0.89994107]
 [0.54429612 0.45570388]
 [0.76279522 0.23720478]
 [0.38611379 0.61388621]
 [0.59491352 0.40508648]
 [0.57210951 0.42789049]
 [0.78537905 0.21462095]
 [0.6297464  0.3702536 ]
 [0.0374025  0.9625975 ]]


In [5]:
e_pred = np.random.rand(10,2)
e_pred[:,1] = 1 - e_pred[:,0]

print(e_pred)


[[0.73864397 0.26135603]
 [0.74891821 0.25108179]
 [0.56794386 0.43205614]
 [0.38510578 0.61489422]
 [0.13869192 0.86130808]
 [0.87235561 0.12764439]
 [0.44070234 0.55929766]
 [0.55818242 0.44181758]
 [0.10887204 0.89112796]
 [0.0827442  0.9172558 ]]


In [8]:
fp = np.argmax(f_pred, axis = 1)
print(fp)

[1 1 0 0 1 0 0 0 0 1]
