In [12]:
import numpy as np


In [25]:
#create array of 50 random integers between 0 and 10
var1 = np.random.randint(0, 10, 3)

#create a positively correlated array with some random noise
var2 = var1 + np.random.normal(0, 10, 3)

In [33]:
#create array of 50 random integers between 0 and 10
var1 = [4,8,2]

#create a positively correlated array with some random noise
var2 = [18,24,-2]

In [34]:
print(np.corrcoef(var1, var2))

[[1.         0.88160953]
 [0.88160953 1.        ]]


In [35]:
def correl(x1, x2):
    
    mean_x1 = np.mean(x1)
    mean_x2 = np.mean(x2)
    
    print(x1, x2)
    
    x1_a = x1 - mean_x1
    x2_a = x2 - mean_x2

    print(x1_a, x2_a)
    print(x1_a * x2_a)

    numerator = np.sum(x1_a * x2_a)
    print('numerator',numerator)
    
    denominator = np.sqrt(np.sum(x1_a * x1_a)) * np.sqrt(np.sum(x2_a * x2_a))
    print('denominator',denominator)
    
    return numerator / denominator
    

In [36]:
c = correl (var1, var2)

print(c)

[4, 8, 2] [18, 24, -2]
[-0.66666667  3.33333333 -2.66666667] [  4.66666667  10.66666667 -15.33333333]
[-3.11111111 35.55555556 40.88888889]
numerator 73.33333333333333
denominator 83.18119445590519
0.8816095250015643
