In [1]:
import numpy as np

In [11]:
a = np.array([16,13,19,11,12,18,17,10,15,14])
print(a)

[16 13 19 11 12 18 17 10 15 14]


In [12]:
b = np.sort(a)
print(b)

[10 11 12 13 14 15 16 17 18 19]


In [18]:
c = np.argpartition(a, -3)[-3:]
print(c)

[6 5 2]


In [19]:
print(a[c])

[17 18 19]


In [20]:
d = np.sort(c)
print(a[d])

[19 18 17]
