In [1]:
from x_distribution import X_distribution
from x_distribution import L_distribution
from x_distribution import Shuffle

import numpy as np

In [2]:
dist = X_distribution(N_features=5, N_ranges=5, N_points=25, bounds=1)

In [3]:
dist = X_distribution(N_features=5, N_ranges=5, N_points=0, bounds=2)

In [4]:
dist = X_distribution(N_features=5, N_ranges=5, N_points=100, bounds=1)

In [5]:
dist = X_distribution(N_features=6, N_ranges=0, N_points=0, bounds=1)

In [9]:
dist = L_distribution(N_features=4, N_points=4, bounds=1)
print(dist)

range_limits [-1.  -0.5  0.   0.5  1. ]
4
[2 3 0 1]
4
[1 0 2 3]
4
[1 2 3 0]
[[-0.6108231   0.20830306 -0.4902979  -0.09939337]
 [-0.2200552   0.89383651 -0.64712453  0.06345119]
 [ 0.10697727 -0.54952161  0.10697331  0.71783607]
 [ 0.81811714 -0.41180182  0.65888113 -0.50247305]]


In [7]:
a = dist.ravel()
print(a)
Shuffle(a)
print(a)

[-0.70040949  0.94423149 -0.12947155  0.06121802  0.23342982 -0.94779081
  0.87647437 -0.43455807]
8
[5 4 6 0 2 1 3 7]
[-0.70040949  0.94423149 -0.12947155  0.06121802  0.23342982 -0.94779081
  0.87647437 -0.43455807]
